### DISCUSSION TITLE
ESP 32 dev

### DISCUSSION THREAD

**Discussion by lucasimons** [syssi/esphome-ant-bms#39] [General]
Now i m installing the new power system i use a esp 32 dev to read the data from inverter, bms and pzem, the logs show the correct value without error, but in Home Assistant i see the stack value and sometimes they are updated, i don t know where is the problem
[logs_sottoscala-esp32-1_logs.txt](https://github.com/syssi/esphome-ant-bms/files/8644778/logs_sottoscala-esp32-1_logs.txt)

there is a delay in the power sensor of bms and solar pannel, they are calculated by volts * amps ?

**Comment by syssi** [comment]
I did not understand what's not working in HA. :-) Could you try to illustrate the issue?

The calculated sensors are updated once per `update_interval`. If the value didn't change the update is suppressed probably.

**Reply by lucasimons** [reply]
this is my config, are there problems with the gpio? because if i update the sofwtware when is connected the pzem the esp doesn t connect with the wifi

    
uart:
- id: uart0
  baud_rate: 19200
  rx_buffer_size: 384
  tx_pin: GPIO16
  rx_pin: GPIO17

- id: uart1
  baud_rate: 2400
  tx_pin: TX
  rx_pin: RX

- id: uart_pzem
  rx_pin: GPIO13
  tx_pin: GPIO23
  baud_rate: 9600
  
pipsolar:
  uart_id: uart1
  id: inverter0




modbus:
- uart_id: uart_pzem
  id: modbus_1 # needed only for multiple buses


ant_modbus:
  id: modbus0
  uart_id: uart0

ant_bms:
  id: bms0
  ant_modbus_id: modbus0
  password: "${password}"
  update_interval: 5s
  supports_new_commands: true



sensor:
  - platform: pipsolar
    pipsolar_id: inverter0

**Reply by syssi** [reply]
Could you provide your full config yaml? I would like to see the `logger` section because the `baud_rate` must be `0` here to avoid conflicts if you use `RX` and `TX` (GPIO1, GPIO3).

**Reply by lucasimons** [reply]
```
substitutions:
  name: bms2
  password: "12345678"

esphome:
  name: sottoscala-esp32-1


external_components:
  - source: github://syssi/esphome-ant-bms@main
    refresh: 0s
    
  - source: github://andreashergert1984/esphome@test_newcrc
    refresh: 0s
    components: [pipsolar]
    
esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API
api:

ota:
  password: "adf359204d6"

wifi:
  networks:
    - ssid: "TP-Link_55C2"
      password: "8xxxxxxxxxxx"

    - ssid: "SeiScarso"
      password: "88xxxxxxxxxxxxx"

  power_save_mode: none
  manual_ip:
    static_ip: 192.168.x.x
    gateway: 192.168.x.x
    subnet: 255.255.255.0    

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sottoscala-Esp32-1"


captive_portal:
    
    
uart:
- id: uart0
  baud_rate: 19200
  rx_buffer_size: 384
  tx_pin: GPIO16
  rx_pin: GPIO17

- id: uart1
  baud_rate: 2400
  tx_pin: TX
  rx_pin: RX

- id: uart_pzem
  rx_pin: GPIO13
  tx_pin: GPIO23
  baud_rate: 9600
  
pipsolar:
  uart_id: uart1
  id: inverter0

modbus:
- uart_id: uart_pzem
  id: modbus_1 # needed only for multiple buses

ant_modbus:
  id: modbus0
  uart_id: uart0

ant_bms:
  id: bms0
  ant_modbus_id: modbus0
  password: "${password}"
  update_interval: 5s
  supports_new_commands: true

sensor:
  - platform: pipsolar
    pipsolar_id: inverter0  
      
    # QPIGS
    grid_voltage:
      name: "inverter grid_voltage"
    grid_frequency:
      name: "inverter grid_frequency"
    ac_output_voltage:
      name: "inverter ac_output_voltage"
    ac_output_frequency:
      name: "inverter ac_output_frequency"
    ac_output_apparent_power:
      name: "inverter ac_output_apparent_power"
    ac_output_active_power:
      name: "inverter ac_output_active_power"
    output_load_percent:
      name: "inverter output_load_percent"
    bus_voltage:
      name: "inverter bus_voltage"
    battery_voltage:
      name: "inverter battery_voltage"
    battery_charging_current:
      name: "inverter battery_charging_current"

    inverter_heat_sink_temperature:
      name: "inverter inverter_heat_sink_temperature"
    pv_input_current_for_battery:
      name: "inverter pv_input_current_for_battery"
    pv_input_voltage:
      name: "inverter pv_input_voltage"

#    eeprom_version:
#      name: "inverter eeprom_version"
    pv_charging_power:
      name: "inverter pv_charging_power"
 
    charger_source_priority:
      name: "inverter charge priority"    
    output_source_priority:   
      name: "inverter output priority"  

  - platform: ant_bms
    battery_strings:
      name: "${name} battery strings"
    current:
      name: "${name} current"
    soc:
      name: "${name} soc"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    capacity_remaining:
      name: "${name} capacity remaining"
    battery_cycle_capacity:
      name: "${name} battery cycle capacity"
    total_voltage:
      name: "${name} total voltage"
    total_runtime:
      name: "${name} total runtime"
    average_cell_voltage:
      name: "${name} average cell voltage"
    power:
      name: "${name} power"
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    temperature_1:
      name: "${name} temperature 1"
    temperature_2:
      name: "${name} temperature 2"
    temperature_3:
      name: "${name} temperature 3"
    temperature_4:
      name: "${name} temperature 4"

    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"  
  - platform: pzemac
    modbus_id: modbus_1
    current:
      name: "Inverter Corrente"
    voltage:
      name: "Inverter Tensione"
    energy:
      name: "Inverter Energia"
    power:
      name: "Inverter Potenza"
    frequency:
      name: "Inverter Frequenza"
    power_factor:
      name: "Inverter Power Factor"
    update_interval: 10s      

  - platform: wifi_signal
    name: "Sottoscala ESP32-1 WiFi Signal Sensor"
    id: rssi_sensor
    update_interval: 5s 



  - platform: uptime
    name: "Sottoscala ESP32-1 Uptime"
    id: uptime_s
    update_interval: 5s    
    
text_sensor:
  - platform: ant_bms
    charge_mosfet_status:
      name: "${name} charge mosfet status"
    discharge_mosfet_status:
      name: "${name} discharge mosfet status"
    balancer_status:
      name: "${name} balancer status"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
      
  - platform: pipsolar
    pipsolar_id: inverter0
    device_mode:
      name: "inverter device_mode"
      
switch:
  - platform: ant_bms
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
  - platform: gpio
    name: "ATS"
    pin: GPIO18
    inverted: true
  - platform: gpio
    name: "Inverter"
    pin: GPIO19
    inverted: true`     
```
