### ISSUE TITLE
Test 2020 version

### ISSUE THREAD

**Issue by lucasimons** [syssi/esphome-ant-bms#31]
Hi, i just received the connector for which i can test with the bms 2020 what should i change to the configuration in esphome?

**Comment by syssi** [comment]
Please set `supports_new_commands` to `false` and provide a password:

```
ant_bms:
  id: bms0
  ant_modbus_id: modbus0
  password: "12345678"
  update_interval: 10s
  supports_new_commands: false
```
