### ISSUE TITLE
Bootloop if the number of sensors exceeds the stack size of an ESP32

### ISSUE THREAD

**Issue by lumiror** [syssi/esphome-ant-bms#36]
Hi, I don't know what I'm doing wrong, but the installation will end with a broken wifi connection. Can you advise on what the problem may be? Or how should I install it properly? Thank you
![error](https://user-images.githubusercontent.com/33359116/161123589-022049fe-7798-47cf-9c0e-9c5f88a839d9.jpg)
[antbms-new.txt](https://github.com/syssi/esphome-ant-bms/files/8392112/antbms-new.txt)

**Comment by syssi** [comment]
Another idea: Please reduce the number of sensors/entities (to a minimum) just for testing. Is the setup stable afterwards?

**Comment by syssi** [comment]
Alright. Please increase the number slowly. I will provide tomorrow a special config setting to increase the stack size of the ESP32 to allow a lot of sensors. At the moment the total number of sensors on the ESP32 platform is a bit limited. I will provide a link to the ESPHome issue too.

**Comment by syssi** [comment]
https://github.com/esphome/issues/issues/855

**Comment by syssi** [comment]
If everything is working a expected I would be happy about the model name or a photo of your ANT-BMS model to extend supported device section of the documentation.

**Comment by lumiror** [comment]
I'll try tomorrow, thank you for now

**Comment by syssi** [comment]
This is some additional configuration to increase the stack size of an **ESP32** to have room for a lot of sensor entities:

https://github.com/esphome/issues/issues/855#issuecomment-1069335461

```
esphome:
  name: power-monitor
  platformio_options:
    build_flags: 
      - -DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768

esp32:
  board: nodemcu-32s
  variant: esp32
  framework:
    type: arduino
    version: 2.0.2
    source: https://github.com/espressif/arduino-esp32.git#2.0.2
    platform_version: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
```

**Comment by lumiror** [comment]
So I tested it, it works. I didn't even have to use the configuration to increase the stack. I only deleted unnecessary sensors, I only have 16 cell batteries. Now I would like to try an older version before 2021, but in the entities I see only entities named ant_bms ..... so only from version 2021 How can I change the name to antbms_old?

**Comment by lumiror** [comment]
This is my version of ANT BMS, unfortunately it has no label
![BMS](https://user-images.githubusercontent.com/33359116/161325521-7cddbb2e-3ab4-45fc-8130-4ba7e9c3759f.jpg)

**Comment by syssi** [comment]
The label at the photo isn't readable. I'm interesting in the full ....-TB-24S-300A string. Could you provide the first few letters?

**Comment by lumiror** [comment]
I tried and it also works but as I wrote in the entities I only see ant_bms from version 2021. But in the log it's right
![Logs](https://user-images.githubusercontent.com/33359116/161327123-475f94a8-7726-4514-8bb7-19643e89d1f0.jpg)

**Comment by syssi** [comment]
I think this is a feature not a bug. ;-) All sensors have a `unique_id` generated via the MAC address of the ESP plus the sensor key (you cannot change). If you use another ESP for the other BMS everything should be fine. If you want to use one ESP for two BMS you have to load the component twice. I assume in this case the uniqe_id of the second pair of sensors is a bit different.

**Comment by lumiror** [comment]
That photo is from aliexpress, here is the original from my BMS.
![IMG_20220401_211049](https://user-images.githubusercontent.com/33359116/161328585-428a5227-0282-4369-adbe-0bbd6d30a7c7.jpg)
![IMG_20220401_211014](https://user-images.githubusercontent.com/33359116/161328664-df04647d-2335-463e-b0cf-d0e2d86434dc.jpg)

**Comment by lumiror** [comment]
I used two ESP32s for each BMS separately but I still see entities only from version 2021

**Comment by lumiror** [comment]
I need to change this name. It is possible
![1](https://user-images.githubusercontent.com/33359116/161329791-71f914ab-d441-4069-9692-437cd0588736.jpg)
?

**Comment by syssi** [comment]
In this case you missed to change the "name:" of the esphome node. The names must be unique per device.

**Comment by syssi** [comment]
Please make sure

```
substitutions:
  name: ant-bms.  # <---- to change this name per ESP / ESPHome node.
  external_components_source: github://syssi/esphome-ant-bms@main
  tx_pin: GPIO1
  rx_pin: GPIO3
  password: "12345678"

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
```
