### ISSUE TITLE
Using entity from ANT BMS to control PWM signal ESP32

### ISSUE THREAD

**Issue by lumiror** [syssi/esphome-ant-bms#46]
Hello, I want to ask, would it be possible to use an entity from ANT BMS in homeassistant, specifically information about the battery charge in % (sensor.antbms_soc) on  pwm signal control from ESP32? For example, if the battery is 95% charged at the ESP32 output, the PWM signal will be 20%, if it is 96% at the output, it will be 35%, 97%=50%, 98%=65%, 99%=85%. 100%=100. Thank you

**Comment by syssi** [comment]
I don't understand you question. All BMS measurements are exposed as sensor entities and available at Home Assistant if you like. I recommend to use the `api` component to make the ESPHome node available/accessible at Home Assistant.

You could extend the YAML configuration to monitor the state of charge entity and control some LEDs to visualize the SoC.

I use something like this: https://de.aliexpress.com/item/4000877848238.html

The ESPHome code looks like this:

```
sensor:
  - platform: ant_bms
    soc:
      name: "${name} soc"
      id: soc

light:
  - platform: neopixelbus
    id: strip
    name: "LED strip"
    type: GRB
    pin: GPIO3
    num_leds: 24
    method: ESP8266_DMA
    variant: WS2812
    restore_mode: ALWAYS_ON
    internal: true

display:
  - platform: addressable_light
    id: gauge
    addressable_light_id: strip
    width: 24
    height: 1
    update_interval: 16ms
    lambda: |-
      float brightness = 0.40f;
      Color color = Color(
        brightness * 0,
        brightness * 255,
        brightness * 0
      );
      if(id(soc) && !isnan(id(soc).state)) {
        int width = std::floor((it.get_width() / 100.0f) * id(soc).state);
        it.line(0, 0, width, 0, color);
      }
```

**Comment by lumiror** [comment]
Thank you for your quick reply. To make it more precise, I would need to control the output PWM signal on the esp32 or ESP 8266 based on the value of the entity, i.e. the battery charge in % (sensor.antbms_soc). As I wrote, if the value of the entity is e.g. 95%, the battery is charged to 95% on the ESP 32 analog output will be 10% PWM signal, etc. I need to use this signal to control the PWM to volt converter from AliExpress.
[https://www.aliexpress.com/item/4000128019142.html?spm=a2g0o.productlist.main.1.317b5c05EgsDj1&algo_pvid=932175f4-5480-4182-8373-3bbf5c35b168&algo_exp_id=932175f4-5480-4182-8373-3bbf5c35b168-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000022229648952%22%7D&pdp_npi=2%40dis%21EUR%211.17%211.17%21%21%21%21%21%40212278f516755152705906314d0665%2112000022229648952%21sea&curPageLogUid=3NRbowooKlIT](url)

**Comment by syssi** [comment]
Is the ESP reading the ANT-BMS and the ESP with the PWM output the same device / ESP?

**Comment by syssi** [comment]
You could use these components to control the PWM of a ESP8266/ESP32:

https://esphome.io/components/output/esp8266_pwm.html
https://esphome.io/components/output/ledc.html

**Comment by lumiror** [comment]
> Is the ESP reading the ANT-BMS and the ESP with the PWM output the same device / ESP?

No ANT-BMS has a separate ESP32

**Comment by syssi** [comment]
Do you prefer a MQTT or a Home Assistant connection?

**Comment by lumiror** [comment]
home assistant 
I found something like this, but I don't know how I could replace that sensor with my own (sensor.antbms_soc)

`output:
  - platform: ledc
    pin: GPIO14
    frequency: 25000 Hz
    id: fan_pwm

fan:
  - platform: speed
    output: fan_pwm
    name: "Network Rack Exhaust Fan Speed"


sensor:
  - platform: bmp280
    i2c_id: bus_b
    address: 0x77
    temperature:
      name: "Network Rack Temperature"
      id: rack_temp
      oversampling: 16x
      on_value:
        then:
          lambda: |-
            if (id(rack_temp).state < 23.0) {
                id(fan_pwm).set_level(0.00);
                ESP_LOGD("PWM", "PWM: 0%");
            }
            else if ((id(rack_temp).state >= 23.0) and (id(rack_temp).state <= 24.0)) {
                id(fan_pwm).set_level(0.05);
                ESP_LOGD("PWM", "PWM: 5%");
            }
            else if ((id(rack_temp).state > 24.0) and (id(rack_temp).state <= 25.0)) {
                id(fan_pwm).set_level(0.1);
                ESP_LOGD("PWM", "PWM: 10%");
            }
            else if ((id(rack_temp).state > 25.0) and (id(rack_temp).state <= 26.0)) {
                id(fan_pwm).set_level(0.2);
                ESP_LOGD("PWM", "PWM: 20%");
            }
            else if ((id(rack_temp).state > 26.0) and (id(rack_temp).state <= 27.0)) {
                id(fan_pwm).set_level(0.3);
                ESP_LOGD("PWM", "PWM: 30%");
            }
            else if ((id(rack_temp).state > 27.0) and (id(rack_temp).state <= 28.0)) {
                id(fan_pwm).set_level(0.4);
                ESP_LOGD("PWM", "PWM: 40%");
            }
            else if ((id(rack_temp).state > 28.0) and (id(rack_temp).state <= 29.0)) {
                id(fan_pwm).set_level(0.5);
                ESP_LOGD("PWM", "PWM: 50%");
            }
            else if ((id(rack_temp).state > 29.0) and (id(rack_temp).state <= 30.0)) {
                id(fan_pwm).set_level(0.6);
                ESP_LOGD("PWM", "PWM: 60%");
            }
            else if ((id(rack_temp).state > 30.0) and (id(rack_temp).state <= 32.0)) {
                id(fan_pwm).set_level(0.7);
                ESP_LOGD("PWM", "PWM: 70%");
            }
            else if ((id(rack_temp).state > 32.0) and (id(rack_temp).state <= 35.0)) {
                id(fan_pwm).set_level(0.8);
                ESP_LOGD("PWM", "PWM: 80%");
            }
            else {
                id(fan_pwm).set_level(1.0);
                ESP_LOGD("ALERT", "OVER 35C! Setting fan to 100%");
            }
            
    update_interval: 2s`

**Comment by syssi** [comment]
Do you prefer a MQTT or a Home Assistant connection between the ESPs?

**Comment by lumiror** [comment]
Home Assistant

**Comment by syssi** [comment]
You can subscribe to any Home Assistant sensor using the `homeassistant` component. It should look like this:

```
api:

output:
  - platform: ledc
    pin: GPIO14
    frequency: 25000 Hz
    id: output_pwm

sensor:
  - platform: homeassistant
    internal: true
    id: soc
    name: "${name} soc"
    entity_id: sensor.ant-bms_soc
    on_value:
      then:
        lambda: |-
          if (id(rack_temp).state < 23.0) {
              id(output_pwm).set_level(0.00);
              ESP_LOGD("PWM", "PWM: 0%");
          }
          else if ((id(rack_temp).state >= 23.0) and (id(rack_temp).state <= 24.0)) {
              id(output_pwm).set_level(0.05);
              ESP_LOGD("PWM", "PWM: 5%");
          }
          else if ((id(rack_temp).state > 24.0) and (id(rack_temp).state <= 25.0)) {
              id(output_pwm).set_level(0.1);
              ESP_LOGD("PWM", "PWM: 10%");
          }
          else if ((id(rack_temp).state > 25.0) and (id(rack_temp).state <= 26.0)) {
              id(output_pwm).set_level(0.2);
              ESP_LOGD("PWM", "PWM: 20%");
          }
          else if ((id(rack_temp).state > 26.0) and (id(rack_temp).state <= 27.0)) {
              id(output_pwm).set_level(0.3);
              ESP_LOGD("PWM", "PWM: 30%");
          }
          else if ((id(rack_temp).state > 27.0) and (id(rack_temp).state <= 28.0)) {
              id(output_pwm).set_level(0.4);
              ESP_LOGD("PWM", "PWM: 40%");
          }
          else if ((id(rack_temp).state > 28.0) and (id(rack_temp).state <= 29.0)) {
              id(output_pwm).set_level(0.5);
              ESP_LOGD("PWM", "PWM: 50%");
          }
          else if ((id(rack_temp).state > 29.0) and (id(rack_temp).state <= 30.0)) {
              id(output_pwm).set_level(0.6);
              ESP_LOGD("PWM", "PWM: 60%");
          }
          else if ((id(rack_temp).state > 30.0) and (id(rack_temp).state <= 32.0)) {
              id(output_pwm).set_level(0.7);
              ESP_LOGD("PWM", "PWM: 70%");
          }
          else if ((id(rack_temp).state > 32.0) and (id(rack_temp).state <= 35.0)) {
              id(output_pwm).set_level(0.8);
              ESP_LOGD("PWM", "PWM: 80%");
          }
          else {
              id(output_pwm).set_level(1.0);
              ESP_LOGD("ALERT", "OVER 35C! Setting fan to 100%");
          }        
```

**Comment by lumiror** [comment]
Thank you very much for your help, I'm going to try it

**Comment by syssi** [comment]
I've fixed a type. Please use the most recent version of the example above.

**Comment by lumiror** [comment]
Can you please look at it again, why it marked line 45 as an error. the API line: I didn't put it there, I already have it in the compilation, is it correct?
![image](https://user-images.githubusercontent.com/33359116/216781880-ecc1632d-3a0b-45f1-8af2-830fab4fd9fb.png)

**Comment by syssi** [comment]
Please goto your Home Assistant instance, open the "Developer Tools -> States" page (`/developer-tools/state`) and search for "soc". Please copy the full entity name of your state of charge entity. Use this entity name at the YAML. May be you have to add quotation marks.

**Comment by lumiror** [comment]
The name seems to be fine
![image](https://user-images.githubusercontent.com/33359116/216783324-f0831c57-8b46-4e26-ad56-9b92d66d6cfe.png)

**Comment by lumiror** [comment]
Oh no, I just destroyed my ESP32. I'm an idiot. I also have an ESP 8266, I can use it or the Output would have to be reconfigured

**Comment by syssi** [comment]
How did you destroy the ESP?

**Comment by syssi** [comment]
If you use a ESP8266 you have to use the `esp8266_pwm` component:

```
output:
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: output_pwm
```

**Comment by lumiror** [comment]
I connected +a- the other way around

**Comment by syssi** [comment]
Okay. ;-) In this case, I also think it is dead.

**Comment by lumiror** [comment]
Thank you very much, I'm going to try it again.

**Comment by lumiror** [comment]
So it works perfectly, I just have one more request for you. Would it be possible to create an entity for the state of the PWM signal so that I can see it in homeassistant? I would be very grateful. And I did not destroy the ESP32, :)  only the diode was destroyed.

**Comment by syssi** [comment]
Hmm... it looks like we cannot ask the `output` for the current PWM. I assume you have to implement a workaround like this:

```
sensor:
  - platform: template
    name: "PWM"
    id: pwm_sensor
  - platform: homeassistant
    internal: true
    id: soc
    name: "${name} soc"
    entity_id: sensor.ant-bms_soc
    on_value:
      then:
        lambda: |-
          if (id(soc).state < 23.0) {
              id(output_pwm).set_level(0.00);
              id(pwm_sensor).publish_state(0.00);
          }
          else if ((id(soc).state >= 23.0) and (id(soc).state <= 24.0)) {
              id(output_pwm).set_level(0.05);
              id(pwm_sensor).publish_state(0.05);
          }
          else if ((id(soc).state > 24.0) and (id(soc).state <= 25.0)) {
              id(output_pwm).set_level(0.1);
              id(pwm_sensor).publish_state(0.1);
          }
          else if ((id(soc).state > 25.0) and (id(soc).state <= 26.0)) {
              id(output_pwm).set_level(0.2);
              id(pwm_sensor).publish_state(0.2);
          }
          else if ((id(soc).state > 26.0) and (id(soc).state <= 27.0)) {
              id(output_pwm).set_level(0.3);
              id(pwm_sensor).publish_state(0.3);
          }
          else {
              id(output_pwm).set_level(1.0);
              id(pwm_sensor).publish_state(1.0);
          }
```

**Comment by lumiror** [comment]
Thank you, but something is not working because the sensor has an unknown value
![image](https://user-images.githubusercontent.com/33359116/216790700-a080dace-490e-4b09-92fb-b22ed911818b.png)

**Comment by lumiror** [comment]
Thank you, it works perfectly

**Comment by syssi** [comment]
Can you explain the purpose of your setup in a few words? What do you drive with the output voltage of the converter? Thanks in advance!

**Comment by lumiror** [comment]
Yes, of course I can. I need to control the water heating in the tank. That is, if the batteries are charged, the water will start to heat up. And in order to use as much energy as possible from the sun, the water heating will start when the battery is charged to approx. 95% and will gradually increase.

**Comment by lumiror** [comment]
Can I ask one more question? Would it be possible to control the PWM signal linearly? That is, on the basis of some value, e.g. 0-20 from the entity and the Pwm signal output would be 0-100%?

**Comment by syssi** [comment]
Could you provide your current configuration / lambda function? I would like to understand which (SoC) value(s) should be translated into another one (PWM percentage).

**Comment by lumiror** [comment]
The value is in Amp, it is the voltage on the solar panels. But it is not an installation on ESP... but on a raspberry and transferred via mqtt to home assistant. It's data from my inverter

**Comment by syssi** [comment]
I'm a bit confused. I need some more details to understand your goal. Yesterday we talked about the SoC and we tried to feed your heater depending on the state of charge in steps. You prefer a linear function instead of steps now. Right? How do you like to take the panel current into account?

**Comment by lumiror** [comment]
What we dealt with yesterday is OK. This is not something else. This is a value from another entity in Amp. Its range is from 0-20A and I would need to linearly convert it to a PWM signal to the ESP 32/2866. so that 0-20A = 0-100% PWM if possible.

**Comment by syssi** [comment]
What do you control with the PWM signal this time? It's the heater again and both solutions should be combined or it's another device? :-)

**Comment by lumiror** [comment]
Exactly, :) I would like to use them together and control the water heating according to them. I wanted to use a Hall current sensor, but this would be better.

**Comment by syssi** [comment]
It's pretty the same like last time. ;-) You can make the sensor state from HA available using this snippet:

```
  - platform: homeassistant
    internal: true
    id: pv_current
    name: "${name} pv current"
    entity_id: sensor.panely_amp
```

The combination of both values is a bit tricky. Could you try to describe the logic in words? Something like: 

1. If the PV current is >10A but the SoC <95%: Set PWM to 100%
2. If the PV current is <10A and the SoC >95%: Set the PWM to 100% too
3. If the PV current is <10A and the SoC <95%: ...

**Comment by lumiror** [comment]
It would be better linearly, not in steps. That is, use the tenth place as well. If, for example, 10A=50% PWM, if 10.1A=50.5%, if 10.2A = 50.1%, etc. Just writing it like before was probably too long, isn't there a formula?

**Comment by syssi** [comment]
I assume you are looking for something like this:

```
sensor:
  - platform: template
    name: "PWM"
    id: pwm_sensor
  - platform: homeassistant
    internal: true
    id: pv_current
    name: "${name} pv current"
    entity_id: sensor.panely_amp
    on_value:
      then:
        lambda: |-
          if(id(pv_current) && !isnan(id(pv_current).state)) {
            float percentage = max(min(id(pv_current).state * 5.0f, 100.0f), 0.0f);

            id(output_pwm).set_level(percentage);
            id(pwm_sensor).publish_state(percentage);
          }
```

On each new "panely_amp" value the PWM is changed according the following formula:

- `pv_current * 5`: 0A * 5 = 0% PWM, 10A * 5 = 50% PWM, 20A * 5 = 100% PWM
- If the result of the calculation is >100% f.e. (21A*5=105% PWM) the min() function returns 100% instead.
- If the result of the calculation is <0% f.e. (-5A*5 = -25% PWM) the max() function returns 0% instead.

**Comment by lumiror** [comment]
It looks great, I'll try it. I just found out that the testing is difficult, because waiting for the real value to change is difficult and I don't have any entities that I would use for the test and on which the value would be changed manually in homeassistant. But I'll manage somehow. Thanks

**Comment by lumiror** [comment]
I still want to ask what happens to the PWM signal if the value in the entity is lost? Because sometimes I lose the connection to the ESP32/2866 and the data is unavailable. The outage lasts approx. 4-6 seconds.

**Comment by syssi** [comment]
The if condition

```
         if(id(pv_current) && !isnan(id(pv_current).state)) {}
```

checks the sensor with the ID `pv_current` exists and provides a value unequal "not a number". At the ESPHome ecosystem the `unavailable` state is encoded as `NaN`. I assume the PWM doesn't get changed if your `pv_current` sensor gets unavailable.

**Comment by lumiror** [comment]
Well, it's not very good if the PWM remains at an unchanged value, especially in the case of permanent malfunctions. Is it not possible to insert some time condition that if the signal is not renewed after xy /sec., the signal will be switched off to 0?

**Comment by syssi** [comment]
What about:

```
sensor:
  - platform: template
    name: "PWM"
    id: pwm_sensor
  - platform: homeassistant
    internal: true
    id: pv_current
    name: "${name} pv current"
    entity_id: sensor.panely_amp
    on_value:
      then:
        lambda: |-
          if(id(pv_current) && !isnan(id(pv_current).state)) {
            float percentage = max(min(id(pv_current).state * 5.0f, 100.0f), 0.0f);

            id(output_pwm).set_level(percentage);
            id(pwm_sensor).publish_state(percentage);
          } else {
            id(output_pwm).set_level(0.0f);
            id(pwm_sensor).publish_state(0.0f);
          }

**Comment by lumiror** [comment]
Does this mean that if there is no value from the entity at the output, the PWM will be 0?

**Comment by syssi** [comment]
Yes!

**Comment by lumiror** [comment]
And this time condition could not be added there, so that the PWM signal is not turned off unnecessarily if the outage is short / one-time

**Comment by syssi** [comment]
I cannot provide more advanced solutions without investing too much time.

**Comment by lumiror** [comment]
I understand clearly, thank you very much for your help anyway. :)

**Comment by syssi** [comment]
Let's close this issue. It's solved! :-)

**Comment by lumiror** [comment]
Yes Thanks.
![image](https://user-images.githubusercontent.com/33359116/216840219-395a605c-9bc5-49f2-a604-137730a24152.png)

**Comment by lumiror** [comment]
Hi, could you help me one more time? I don't know why, but I still have 100% voltage on the "PWM1" output of GPIO27 in my test circuit. The formula seems to be fine 0-20V=0-100%, but in reality the PWM signal on the GPIO27 output does not change and is still as I wrote 100% . "PWM" on the GPIO25 output works correctly. Thank you

**Comment by lumiror** [comment]
I measured it and it looks like there is probably no signal there, only the output is high. Because there is a frequency of 25KHz on the output of GPIO25. But there is no frequency on the output of GDPO27.

**Comment by syssi** [comment]
Could you provide your configuration YAML? I would like to reproduce the issue locally.

**Comment by lumiror** [comment]
This?

![image](https://user-images.githubusercontent.com/33359116/218190342-da4224ce-9ca7-4488-bde7-de3acccaccfe.png)

**Comment by syssi** [comment]
Could you try to assign adjacent channels to the `ledc` instances:

```
output:
 - platform: ledc
   pin: GPIO25
   frequency: 25000 Hz
   id: output_pwm
   channel: 0
 - platform: ledc  
   pin: GPIO27
   frequency: 25000 Hz
   id: output1_pwm
   channel: 1
```

**Comment by lumiror** [comment]
Unfortunately, it does not work, there is no frequency on the output

**Comment by syssi** [comment]
Could you try another GPIO? May be GPIO25 is always pulled up for unknown reason?

**Comment by lumiror** [comment]
GPIO25 is ok and also GPIO27. I also tried replacing PWM with PWM1 and the GPIO27 output worked normally. But then again GPIO 25 was high and without frequency

**Comment by syssi** [comment]
It sounds like there is an issue if you use two PWMs simultaneously?

**Comment by lumiror** [comment]
Tomorrow I will try just one PWM output and see if it will work. But what I looked on the net, they usually use 2 PWM outputs on the ESP32.

**Comment by syssi** [comment]
The ESP32 has 16 PWMs channels. Every output pin is supported. It's pretty common to use three adjacent PWMs to drive the three channels of an RGB LED lamp.

**Comment by lumiror** [comment]
I tried the flood configuration with sensor.panely_amp but it still doesn't work, I have the same result, the output is high but without frequency. It should now be 13.5% since the current is 2.7A. You don't know what the problem could be?

![image](https://user-images.githubusercontent.com/33359116/218250575-d083c599-6914-493e-86b9-0018cf834623.png)


 ```
esphome:
  name: solar-bla

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  password: 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solar-Bla Fallback Hotspot"
    password: 

captive_portal:
  
output:
  - platform: ledc
    pin: GPIO14
    frequency: 25000 Hz
    id: output_pwm  
  
sensor:
  - platform: template
    name: "PWM"
    id: pwm_sensor
  - platform: homeassistant
    internal: true
    id: pv_current
    name: "${name} pv current"
    entity_id: sensor.panely_amp
    on_value:
      then:
        lambda: |-
          if(id(pv_current) && !isnan(id(pv_current).state)) {
            float percentage = max(min(id(pv_current).state * 5.0f, 100.0f), 0.0f);
            
            id(output_pwm).set_level(percentage);
            id(pwm_sensor).publish_state(percentage);
          }
 ```

**Comment by syssi** [comment]
I assume the high frequency of `25000 Hz` is the root cause and you voltage converter isn't able to recognize the pulses because it looks like a single high signal (because of the speed).

**Comment by lumiror** [comment]
I'll try less, about 1000 Hz. But it is strange that the output on GPIO25 works correctly even at a frequency of 2500Hz

**Comment by lumiror** [comment]
So no change, even at 1000Hz I will try even less 500Hz

**Comment by syssi** [comment]
This is my test bench setup:

```
esphome:
  name: pwm-test

esp32:
  # board: esp32dev
  board: wemos_d1_mini32
  framework:
    type: arduino

logger:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

output:
  - platform: ledc
    pin: GPIO25
    id: output_pwm0
  - platform: ledc
    pin: GPIO26
    id: output_pwm1

light:
  - platform: monochromatic
    name: "pwm0"
    id: pwm0_light
    output: output_pwm0
  - platform: monochromatic
    name: "pwm1"
    id: pwm1_light
    output: output_pwm1
```

I can control the PWM using the brightness of the light entities at Home Assistant. If I measure the voltage between `GPIO25/GPIO26` and `GND` I can measure a voltage between 0V and 3.3V depending on the brightness/PWM.

**Comment by lumiror** [comment]
And how do you control the brightness? I have it based on the entity, but you don't have it there

**Comment by syssi** [comment]
If you use the `api` component and register the ESPHome node at Home Assistant the `light` entity looks like this:

![light](https://user-images.githubusercontent.com/2735933/218252855-68e84292-c10d-432e-bb5d-08785edc589d.png)

I've used the brightness slide to change/set the PWM and measured the voltage at the PWM pin to make sure it's working.

**Comment by lumiror** [comment]
And how do you control the brightness? I have it based on the entity, but you don't have it there

**Comment by syssi** [comment]
It's hard to guess because you didn't try to rule out root causes yet. Please try to follow these steps:

1. Use my `pwm-test` YAML from above & make the ESPHome node available at Home Assistant
2. Are you able to click on the two light entities and control the brights?
3. Disconnect your voltage converters and use a multimeter to measure the voltage a the PWM pins. Are you able to control the measured voltage using the brightness slides of both outputs/lights?
4. If both PWMs pins are working as expected please attach the voltage converters again. Are you able to control the converters using the brightness slider? Does your converter respond properly to the brightness setting?
5. Remove the light entities from the test-pwm yaml. Add the template sensor and the `on_value` rules again. Does it work now?

**Comment by lumiror** [comment]
Your test works for me too. I tried GPIO 25,26,27,14 and they all work normally. But if I put back the template sensor and the on_value rules, it does not work

**Comment by syssi** [comment]
Interesting. I will refactor your YAML above. Instead of controlling the `output` entity directly and storing the setting at a template sensor we will use the `light` entity here too because it's easier to debug.

**Comment by syssi** [comment]
Please try this YAML:

```
esphome:
 name: pwm-test

esp32:
 board: esp32dev
 framework:
   type: arduino

logger:
api:
ota:

wifi:
 ssid: !secret wifi_ssid
 password: !secret wifi_password
 
output:
  - platform: ledc
    pin: GPIO25
    id: output_pwm0
  - platform: ledc
    pin: GPIO26
    id: output_pwm1

light:
  - platform: monochromatic
    name: "pwm0"
    id: light_pwm0
    output: output_pwm0
    gamma_correct: 0
    default_transition_length: 0s
  - platform: monochromatic
    name: "pwm1"
    id: light_pwm1
    output: output_pwm1
    gamma_correct: 0
    default_transition_length: 0s

sensor:
 - platform: homeassistant
   internal: true
   id: pv_current
   name: "${name} pv current"
   entity_id: sensor.panely_amp
   on_value:
     then:
       lambda: |-
         if(id(pv_current) && !isnan(id(pv_current).state)) {
           float percentage = max(min(id(pv_current).state * 5.0f, 100.0f), 0.0f);
           id(light_pwm0).turn_on().set_brightness(percentage).perform();
         }

```
